export enum ScreenName {
    Home = 'Home',
    Login = 'Login',
    InfoEmployer = 'InfoEmployer',
    CreateEmployer = 'CreateEmployer',
    HomeEmployer = 'HomeEmployer',
    Profile = 'Profile',
    JobPost = 'JobPost',
    JobList = 'JobList',
    JobDetail = 'JobDetail',
    SearchScreen = 'SearchScreen',
    CVCreate = 'CVCreate',
    ApplyManager = 'ApplyManager',
    MessageScreen = 'MessageScreen',
    InforManager = 'InforManager',
    EmployerDetail = "EmployerDetail",
    CVManagerment = 'CVManagerment',
    ManageCVsApplied = "ManageCVsApplied",
    FavoriteJob = "FavoriteJob",
    CVDetail = "CVDetail",
    SendSMS = "SendSMS",
    EditCV = "EditCV",
    EditInfoEmployer = "EditInfoEmployer",
    CVInfor = "CVInfor",
}
export default ScreenName;

