export enum ScreenName {
    Home = 'Home',
    Login = 'Login',
    CreateEmployer = 'CreateEmployer',
    InforEmployer = 'InforEmployer',
    HomeEmployer = 'HomeEmployer',
    Profile = 'Profile',
    JobPost = 'JobPost',
    JobList = 'JobList',
    JobDetail = 'JobDetail',
    CVCreate = 'CVCreate',
    ApplyManager = 'ApplyManager',
    InforEmployers = 'InforEmployers',
    MessageScreen = 'MessageScreen',
    InforManager = 'InforManager',
    EmployerDetail = "EmployerDetail",
    CVManagerment = 'CVManagerment',
    ManageCVsApplied = "ManageCVsApplied",
}
export default ScreenName;