export type RootStackParamList = {
    Home: undefined;
    Login: undefined;
    CreateEmployer: undefined;
    InforEmployer: undefined;
    HomeEmployer: undefined;
    Profile: undefined;
    JobPost: undefined;
    JobList: undefined;
    CVCreate: undefined;
    ApplyManager: undefined;
    InforEmployers: undefined;
    MessageScreen: undefined;
    JobDetail:{ jobId: string };
    CvDetail: undefined;
    InforManager: undefined;
    EmployerDetail: { jobId: string };
    CVManagerment: undefined;
};
export default RootStackParamList;