export type RootStackParamList = {
    Home: undefined;
    Login: undefined;
    CreateEmployer: undefined;
    InforEmployer: undefined;
    HomeEmployer: undefined;
    Profile: { userEmail: string };
    JobPost: undefined;
    JobList1: { location: string, query: string };
    SearchSceen: { searchType: string };
    CVCreate: undefined;
    InforEmployers: undefined;
    MessageScreen: undefined;
    CvDetail: undefined;
    ApplyManager: { jobId: string };
    InforManager: undefined;
    EmployerDetail: { jobId: string };
    CVManagerment: undefined;
    JobDetail: { jobId: string };
};
export default RootStackParamList;